package com.example.ui

object SageLocalizer {
    private val en = mapOf(
        "app_tagline" to "Life Finance Companion",
        "dashboard" to "Dashboard",
        "bills" to "Bills",
        "allocate" to "Allocate",
        "profile" to "Profile",
        "safe_to_use" to "Safe To Use",
        "free_spending" to "Free Spending",
        "savings" to "Total Savings",
        "current_priority" to "Current Priority Bill",
        "next_bill_due" to "Next Bill Due",
        "living_fund_remaining" to "Living Fund Remaining",
        "suggested_daily" to "Suggested Daily Spend",
        "days_to_payday" to "Days Until Payday",
        "days" to "Days",
        "weekly_commitment" to "Weekly Commitment Summary",
        "this_week" to "This Week",
        "next_week" to "Next Week",
        "next_month" to "Next Month",
        "bills_ending_soon" to "Bills Ending Soon",
        "upcoming_before_payday" to "Upcoming Bills Before Payday",
        "additional_income" to "Additional Income Needed",
        "rama_ledger" to "Rama's Ledger",
        "nadiya_ledger" to "Nadiya's Ledger",
        "kos_shared" to "Kos (Shared Rent)",
        "progress" to "Progress",
        "remaining" to "Remaining",
        "rama_contrib" to "Rama",
        "nadiya_contrib" to "Nadiya",
        "bill_allocation_system" to "Bill Allocation System",
        "reserved" to "Reserved",
        "forecast_mode" to "Forecast Simulator",
        "forecast_active_desc" to "Viewing simulated projection. Real data is NOT changed.",
        "today" to "Today",
        "next_day" to "Next Day",
        "prev_day" to "Prev Day",
        "add_7d" to "+7 Days",
        "add_30d" to "+30 Days",
        "reset_today" to "Reset Today",
        "add_income_title" to "Add Income (Priority Allocation)",
        "amount_to_allocate" to "Amount to Allocate",
        "priority_allocation_flow" to "Priority Allocation Steps:",
        "step_1_laundry" to "Step 1: Laundry Reserve",
        "step_2_living" to "Step 2: Living Fund Share",
        "step_3_rent" to "Step 3: Share Rent (Kos) Contribution",
        "step_4_bills" to "Step 4: Due Bills Allocation",
        "step_5_savings" to "Step 5: Savings",
        "step_6_free" to "Step 6: Free Spending (Residual)",
        "suggest_nearest_bill" to "Suggested Due Bill(s)",
        "allocate_btn" to "Confirm Smart Allocation",
        "personal_mode" to "Personal Mode",
        "couple_mode" to "Couple Mode",
        "edit_user" to "Edit Profile",
        "add_user" to "Add Partner",
        "settings" to "Settings",
        "backup_maintenance" to "Backup & Maintenance",
        "export_backup" to "Export Backup JSON",
        "import_backup" to "Import Backup JSON",
        "reset_all_data" to "Reset App Database",
        "reset_prompt" to "Type 'RESET' to permanently erase all custom budgets, balances, and configurations.",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "active_bills" to "Current Month Bills",
        "upcoming_bills" to "Upcoming Bills",
        "completed_bills" to "Completed Bills",
        "add_bill" to "Add Custom Bill",
        "save" to "Save",
        "delete" to "Delete",
        "mark_paid" to "Mark Paid",
        "mark_completed" to "Mark Completed",
        "no_priority" to "All current bills allocated!",
        "unallocated" to "Unallocated",
        "bill_added_msg" to "Bill Added successfully!",
        "bill_updated_msg" to "Bill Updated successfully!",
        "bill_deleted_msg" to "Bill Deleted successfully!",
        "notifications" to "Notifications",
        "enable_notifications" to "Enable Notifications",
        "notifications_desc" to "Receive alert reminders for offline unpaid bills."
    )

    private val id = mapOf(
        "app_tagline" to "Teman Keuangan Hidup",
        "dashboard" to "Dasbor",
        "bills" to "Tagihan",
        "allocate" to "Alokasi",
        "profile" to "Profil",
        "safe_to_use" to "Aman Digunakan",
        "free_spending" to "Uang Jajan",
        "savings" to "Total Tabungan",
        "current_priority" to "Tagihan Prioritas Unit",
        "next_bill_due" to "Tagihan Berikutnya",
        "living_fund_remaining" to "Dana Hidup Tersisa",
        "suggested_daily" to "Saran Jajan Harian",
        "days_to_payday" to "Hari Hingga Hari Gaji",
        "days" to "Hari",
        "weekly_commitment" to "Ringkasan Komitmen Mingguan",
        "this_week" to "Minggu Ini",
        "next_week" to "Minggu Depan",
        "next_month" to "Bulan Depan",
        "bills_ending_soon" to "Tagihan Segera Berakhir",
        "upcoming_before_payday" to "Tagihan Hingga Hari Gaji",
        "additional_income" to "Kebutuhan Tambahan Penghasilan",
        "rama_ledger" to "Buku Rama",
        "nadiya_ledger" to "Buku Nadiya",
        "kos_shared" to "Uang Kos (Sewa Bersama)",
        "progress" to "Progres",
        "remaining" to "Sisa Kurang",
        "rama_contrib" to "Rama",
        "nadiya_contrib" to "Nadiya",
        "bill_allocation_system" to "Sistem Alokasi Tagihan (Bukan Bayar)",
        "reserved" to "Disisihkan (Alokasi)",
        "forecast_mode" to "Simulator Proyeksi",
        "forecast_active_desc" to "Melihat proyeksi visual. Data asli TIDAK berubah.",
        "today" to "Hari Ini",
        "next_day" to "Besok",
        "prev_day" to "Kemarin",
        "add_7d" to "+7 Hari",
        "add_30d" to "+30 Hari",
        "reset_today" to "Reset Hari Ini",
        "add_income_title" to "Catat Pendapatan (Sistem Alokasi)",
        "amount_to_allocate" to "Jumlah Pendapatan",
        "priority_allocation_flow" to "Alur Prioritas Alokasi Sesuai Aturan:",
        "step_1_laundry" to "Prioritas 1: Cadangan Laundry",
        "step_2_living" to "Prioritas 2: Dana Hidup Harian",
        "step_3_rent" to "Prioritas 3: Patungan Kos (Sewa)",
        "step_4_bills" to "Prioritas 4: Tabungan Alokasi Tagihan",
        "step_5_savings" to "Prioritas 5: Tabungan",
        "step_6_free" to "Prioritas 6: Sisa Uang Jajan Bebas",
        "suggest_nearest_bill" to "Saran Tagihan Terdekat",
        "allocate_btn" to "Konfirmasi Alokasi Pintar",
        "personal_mode" to "Mode Personal",
        "couple_mode" to "Mode Pasangan",
        "edit_user" to "Ubah Profil",
        "add_user" to "Tambah Pasangan",
        "settings" to "Pengaturan",
        "backup_maintenance" to "Cadangan & Pemeliharaan",
        "export_backup" to "Ekspor Cadangan JSON",
        "import_backup" to "Impor Cadangan JSON",
        "reset_all_data" to "Hapus Seluruh Data",
        "reset_prompt" to "Ketik 'RESET' untuk menghapus permanen anggaran, saldo, lunas, dan setelan Anda.",
        "confirm" to "Konfirmasi",
        "cancel" to "Batal",
        "active_bills" to "Tagihan Bulan Ini",
        "upcoming_bills" to "Tagihan Akan Datang",
        "completed_bills" to "Tagihan Lunas / Selesai",
        "add_bill" to "Tambah Tagihan Baru",
        "save" to "Simpan",
        "delete" to "Hapus",
        "mark_paid" to "Tandai Lunas",
        "mark_completed" to "Tandai Selesai",
        "no_priority" to "Semua tagihan lunas teralokasi!",
        "unallocated" to "Sisa bebas",
        "bill_added_msg" to "Tagihan berhasil ditambahkan!",
        "bill_updated_msg" to "Tagihan berhasil diperbarui!",
        "bill_deleted_msg" to "Tagihan berhasil dihapus!",
        "notifications" to "Notifikasi",
        "enable_notifications" to "Aktifkan Notifikasi",
        "notifications_desc" to "Terima pengingat peringatan untuk tagihan belum lunas secara offline."
    )

    fun t(key: String, lang: String): String {
        val map = if (lang.lowercase() == "id") id else en
        return map[key] ?: en[key] ?: key
    }
}
